"""`docs/known-issues.md` is derived from the bug corpus, and this is what makes that true.

The page says a release discloses every open Medium and Low finding by id. A disclosure
maintained by hand decays in the direction that flatters: a bug filed after the page was
written is simply absent, and nothing notices. So the page is generated by
`tools/known_issues.py`, and here the shipped page is compared against what the corpus
implies - in both directions, so a missing row and a stale row each fail.

The page is compared through the GENERATOR rather than by re-deriving the corpus a second
time here. A test that reimplements its subject agrees with itself: both copies would have
to be wrong in the same way to disagree, which is the failure mode a second implementation
is supposed to catch and cannot.

Mutants this must fail on: delete a row from the table; add a row for a bug that is not
open; change the `38 findings: 37 Medium, 1 Low` line without changing the table; change a
row's severity cell; make the generator drop the Low severity from its disclosed set.
"""

from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import known_issues as ki  # noqa: E402


class KnownIssuesPageTests(unittest.TestCase):
    """The shipped page against the shipped corpus."""

    def test_page_exists(self):
        self.assertTrue((ki.REPO / ki.PAGE_REL).exists(),
                        f"{ki.PAGE_REL} is the release disclosure and is missing")

    def test_every_open_medium_or_low_bug_is_disclosed(self):
        missing = sorted(set(ki.corpus()) - set(ki.listed()))
        self.assertEqual(
            [], missing,
            "open findings absent from docs/known-issues.md - a release would ship them "
            f"undisclosed: {', '.join(missing)}",
        )

    def test_nothing_is_listed_that_is_not_open(self):
        extra = sorted(set(ki.listed()) - set(ki.corpus()))
        self.assertEqual(
            [], extra,
            "docs/known-issues.md lists findings that are not open at a disclosed "
            f"severity - the page is stale: {', '.join(extra)}",
        )

    def test_severities_agree_with_the_corpus(self):
        page, real = ki.listed(), ki.corpus()
        wrong = {b: (page[b], real[b][0]) for b in sorted(set(page) & set(real))
                 if page[b] != real[b][0]}
        self.assertEqual({}, wrong, f"severity disagrees with the bug file: {wrong}")

    def test_the_stated_counts_are_read_from_the_table(self):
        """The prose states a total and a split. Both are derived here, so neither can drift."""
        page = ki.listed()
        total = len(page)
        mediums = sum(1 for s in page.values() if s == "Medium")
        lows = sum(1 for s in page.values() if s == "Low")
        text = (ki.REPO / ki.PAGE_REL).read_text(encoding="utf-8")
        expected = f"{total} findings: {mediums} Medium, {lows} Low."
        self.assertIn(
            expected, text,
            f"the page's count line does not match its own table; it should read: {expected}",
        )

    def test_the_shipped_page_is_byte_identical_to_what_the_generator_produces(self):
        """The strongest form of the claim, and the one that catches a hand-edit anywhere on the
        page rather than only inside the table."""
        have = (ki.REPO / ki.PAGE_REL).read_text(encoding="utf-8")
        self.assertEqual(ki.render(), have,
                         "docs/known-issues.md has been hand-edited - regenerate it with "
                         "`python3 tools/known_issues.py --write`")


class GeneratorTests(unittest.TestCase):
    """The generator's own rules, on a fixture, so they are pinned independently of the corpus."""

    def _corpus(self, *bugs: tuple[str, str, str, str]) -> Path:
        """Build a throwaway bug corpus. `(id, status, severity, title)` per bug."""
        root = Path(tempfile.mkdtemp(prefix="known_issues_"))
        (root / ki.BUGS_REL).mkdir(parents=True)
        (root / "docs").mkdir(parents=True)
        for bug_id, status, severity, title in bugs:
            (root / ki.BUGS_REL / f"{bug_id}-x.md").write_text(
                f"# {bug_id}: {title}\n\n"
                f"> **Status:** {status}\n> **Severity:** {severity}\n", encoding="utf-8")
        return root

    def test_a_high_finding_is_never_disclosed_here(self):
        """High is the BAR, not the residue. One appearing would mean the bar had been dropped
        rather than met, and the page would report a decision nobody recorded."""
        root = self._corpus(("BG0001", "Open", "High", "a blocker"),
                            ("BG0002", "Open", "Medium", "a residue"))
        self.assertEqual({"BG0002"}, set(ki.corpus(root)))

    def test_a_terminal_finding_leaves_the_list(self):
        root = self._corpus(("BG0001", "Fixed", "Medium", "repaired"),
                            ("BG0002", "Won't Fix", "Medium", "ruled out"),
                            ("BG0003", "Open", "Medium", "still open"))
        self.assertEqual({"BG0003"}, set(ki.corpus(root)))

    def test_the_low_finding_is_not_lost_in_the_middle_of_the_table(self):
        """Low sorts first. One Low among 37 Mediums, sorted by id, would land unfindable in the
        middle of the table - present, and disclosed in the same sense a footnote is."""
        root = self._corpus(("BG0001", "Open", "Medium", "m"), ("BG0009", "Open", "Low", "l"))
        rows = [ln for ln in ki.render(root).splitlines() if ln.startswith("| `BG")]
        self.assertTrue(rows[0].startswith("| `BG0009` | Low |"), rows)

    def test_a_long_title_is_elided_rather_than_left_to_wrap(self):
        root = self._corpus(("BG0001", "Open", "Medium", "t" * 400))
        row = next(ln for ln in ki.render(root).splitlines() if ln.startswith("| `BG0001`"))
        self.assertIn("...", row)
        self.assertLess(len(row), ki.TITLE_MAX + 60)

    def test_check_refuses_when_the_page_disagrees_with_the_corpus(self):
        """The refusal is the point of the generator: `--check` is what a lane can run."""
        root = self._corpus(("BG0001", "Open", "Medium", "m"))
        (root / ki.PAGE_REL).write_text("# Known issues\n\nnothing to see\n", encoding="utf-8")
        self.assertEqual(1, ki.main(["--check", "--root", str(root)]))

    def test_a_bare_invocation_refuses_rather_than_defaulting_to_either_mode(self):
        """A generator that writes by default rewrites the page for anyone who runs it to see what
        it does; one that checks by default makes `--check` a switch that changes nothing. Both
        modes are stated."""
        root = self._corpus(("BG0001", "Open", "Medium", "m"))
        with self.assertRaises(SystemExit) as caught:
            ki.main(["--root", str(root)])
        self.assertEqual(2, caught.exception.code)

    def test_write_then_check_agrees(self):
        """The positive control. Without it, a `--check` that always refused would pass the test
        above for entirely the wrong reason."""
        root = self._corpus(("BG0001", "Open", "Medium", "m"))
        self.assertEqual(0, ki.main(["--write", "--root", str(root)]))
        self.assertEqual(0, ki.main(["--check", "--root", str(root)]))


class ReleaseBarTests(unittest.TestCase):
    """The bar itself: `--bar` is what makes "zero open High" a check rather than a sentence.

    Deliberately NOT asserted against the live corpus here. An open High finding is ordinary
    mid-sprint and is a defect only at the tag, so a per-commit test that demanded zero would
    be red for most of a release cycle and would be switched off. The behaviour is pinned on
    fixtures; the live reading belongs on the release path.
    """

    def _corpus(self, *bugs):
        root = Path(tempfile.mkdtemp(prefix="release_bar_"))
        (root / ki.BUGS_REL).mkdir(parents=True)
        (root / "docs").mkdir(parents=True)
        for bug_id, status, severity in bugs:
            (root / ki.BUGS_REL / f"{bug_id}-x.md").write_text(
                f"# {bug_id}: t\n\n> **Status:** {status}\n> **Severity:** {severity}\n",
                encoding="utf-8")
        return root

    def test_an_open_high_finding_fails_the_bar(self):
        root = self._corpus(("BG0001", "Open", "High"), ("BG0002", "Open", "Medium"))
        self.assertEqual(1, ki.main(["--bar", "--root", str(root)]))

    def test_an_open_critical_finding_fails_the_bar(self):
        """Critical is barred too. A bar that only reads High would let the worse case through."""
        root = self._corpus(("BG0001", "Open", "Critical"))
        self.assertEqual(1, ki.main(["--bar", "--root", str(root)]))

    def test_a_disclosed_residue_alone_meets_the_bar(self):
        """The positive control, and the whole point of D0136: Medium and Low ship OPEN."""
        root = self._corpus(("BG0001", "Open", "Medium"), ("BG0002", "Open", "Low"))
        self.assertEqual(0, ki.main(["--bar", "--root", str(root)]))

    def test_a_fixed_high_finding_does_not_hold_the_bar(self):
        root = self._corpus(("BG0001", "Fixed", "High"), ("BG0002", "Won't Fix", "High"))
        self.assertEqual(0, ki.main(["--bar", "--root", str(root)]))

    def test_the_bar_and_the_residue_are_separate_reads(self):
        """Folding the bar into a filter over the disclosed set is how a residue check ends up
        standing in for a bar check. A High finding must appear in NEITHER list."""
        root = self._corpus(("BG0001", "Open", "High"))
        self.assertEqual({}, ki.corpus(root))
        self.assertEqual({"BG0001": "High"}, ki.barred_open(root))


class ReleaseNotesClaimTests(unittest.TestCase):
    """The hand-authored notes state a count in prose. Prose drifts; this is what stops it."""

    def test_the_notes_state_the_number_of_findings_the_corpus_holds(self):
        notes = (ki.REPO / ki.NOTES_REL).read_text(encoding="utf-8")
        found = ki.corpus()
        mediums = sum(1 for s, _t in found.values() if s == "Medium")
        lows = sum(1 for s, _t in found.values() if s == "Low")
        expected = (f"**v5.0.0 ships with {len(found)} open defects: {mediums} Medium, "
                    f"{lows} Low. Zero Critical, zero High.**")
        self.assertIn(
            expected, notes,
            "the release notes state a finding count the bug corpus contradicts. It should "
            f"read:\n  {expected}")


if __name__ == "__main__":
    unittest.main()
