"""`docs/known-issues.md` is derived from the bug corpus, and this is what makes that true.

The page says a release discloses every open Medium and Low finding by id. A disclosure
maintained by hand decays in the direction that flatters: a bug filed after the page was
written is simply absent, and nothing notices. So the page is generated by
`tools/known_issues.py`, and here the shipped page is compared against what the corpus
implies - in both directions, so a missing row and a stale row each fail.

The page is compared through the GENERATOR rather than by re-deriving the corpus a second
time here. A test that reimplements its subject agrees with itself: both copies would have
to be wrong in the same way to disagree, which is the failure mode a second implementation
is supposed to catch and cannot.

Mutants this must fail on: delete a row from the table; add a row for a bug that is not
open; change the `38 findings: 37 Medium, 1 Low` line without changing the table; change a
row's severity cell; make the generator drop the Low severity from its disclosed set.
"""

from __future__ import annotations

import contextlib
import io
import re
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import known_issues as ki  # noqa: E402


class KnownIssuesPageTests(unittest.TestCase):
    """The shipped page against the shipped corpus."""

    def test_page_exists(self):
        self.assertTrue((ki.REPO / ki.PAGE_REL).exists(),
                        f"{ki.PAGE_REL} is the release disclosure and is missing")

    def test_every_open_medium_or_low_bug_is_disclosed(self):
        missing = sorted(set(ki.corpus()) - set(ki.listed()))
        self.assertEqual(
            [], missing,
            "open findings absent from docs/known-issues.md - a release would ship them "
            f"undisclosed: {', '.join(missing)}",
        )

    def test_nothing_is_listed_that_is_not_open(self):
        extra = sorted(set(ki.listed()) - set(ki.corpus()))
        self.assertEqual(
            [], extra,
            "docs/known-issues.md lists findings that are not open at a disclosed "
            f"severity - the page is stale: {', '.join(extra)}",
        )

    def test_severities_agree_with_the_corpus(self):
        page, real = ki.listed(), ki.corpus()
        wrong = {b: (page[b], real[b][0]) for b in sorted(set(page) & set(real))
                 if page[b] != real[b][0]}
        self.assertEqual({}, wrong, f"severity disagrees with the bug file: {wrong}")

    def test_the_stated_counts_are_read_from_the_table(self):
        """The prose states a total and a split. Both are derived here, so neither can drift."""
        page = ki.listed()
        total = len(page)
        mediums = sum(1 for s in page.values() if s == "Medium")
        lows = sum(1 for s in page.values() if s == "Low")
        text = (ki.REPO / ki.PAGE_REL).read_text(encoding="utf-8")
        expected = f"{total} findings: {mediums} Medium, {lows} Low."
        self.assertIn(
            expected, text,
            f"the page's count line does not match its own table; it should read: {expected}",
        )

    def test_the_shipped_page_is_byte_identical_to_what_the_generator_produces(self):
        """The strongest form of the claim, and the one that catches a hand-edit anywhere on the
        page rather than only inside the table."""
        have = (ki.REPO / ki.PAGE_REL).read_text(encoding="utf-8")
        self.assertEqual(ki.render(), have,
                         "docs/known-issues.md has been hand-edited - regenerate it with "
                         "`python3 tools/known_issues.py --write`")


class GeneratorTests(unittest.TestCase):
    """The generator's own rules, on a fixture, so they are pinned independently of the corpus."""

    def _corpus(self, *bugs: tuple[str, str, str, str]) -> Path:
        """Build a throwaway bug corpus. `(id, status, severity, title)` per bug."""
        root = Path(tempfile.mkdtemp(prefix="known_issues_"))
        (root / ki.BUGS_REL).mkdir(parents=True)
        (root / "docs").mkdir(parents=True)
        for bug_id, status, severity, title in bugs:
            (root / ki.BUGS_REL / f"{bug_id}-x.md").write_text(
                f"# {bug_id}: {title}\n\n"
                f"> **Status:** {status}\n> **Severity:** {severity}\n", encoding="utf-8")
        return root

    def test_a_high_finding_is_never_disclosed_here(self):
        """High is the BAR, not the residue. One appearing would mean the bar had been dropped
        rather than met, and the page would report a decision nobody recorded."""
        root = self._corpus(("BG0001", "Open", "High", "a blocker"),
                            ("BG0002", "Open", "Medium", "a residue"))
        self.assertEqual({"BG0002"}, set(ki.corpus(root)))

    def test_a_terminal_finding_leaves_the_list(self):
        root = self._corpus(("BG0001", "Fixed", "Medium", "repaired"),
                            ("BG0002", "Won't Fix", "Medium", "ruled out"),
                            ("BG0003", "Open", "Medium", "still open"))
        self.assertEqual({"BG0003"}, set(ki.corpus(root)))

    def test_the_low_finding_is_not_lost_in_the_middle_of_the_table(self):
        """Low sorts first. One Low among 37 Mediums, sorted by id, would land unfindable in the
        middle of the table - present, and disclosed in the same sense a footnote is."""
        root = self._corpus(("BG0001", "Open", "Medium", "m"), ("BG0009", "Open", "Low", "l"))
        rows = [ln for ln in ki.render(root).splitlines() if ln.startswith("| `BG")]
        self.assertTrue(rows[0].startswith("| `BG0009` | Low |"), rows)

    def test_a_long_title_is_elided_rather_than_left_to_wrap(self):
        root = self._corpus(("BG0001", "Open", "Medium", "t" * 400))
        row = next(ln for ln in ki.render(root).splitlines() if ln.startswith("| `BG0001`"))
        self.assertIn("...", row)
        self.assertLess(len(row), ki.TITLE_MAX + 60)

    def test_check_refuses_when_the_page_disagrees_with_the_corpus(self):
        """The refusal is the point of the generator: `--check` is what a lane can run."""
        root = self._corpus(("BG0001", "Open", "Medium", "m"))
        (root / ki.PAGE_REL).write_text("# Known issues\n\nnothing to see\n", encoding="utf-8")
        self.assertEqual(1, ki.main(["--check", "--root", str(root)]))

    def test_a_bare_invocation_refuses_rather_than_defaulting_to_either_mode(self):
        """A generator that writes by default rewrites the page for anyone who runs it to see what
        it does; one that checks by default makes `--check` a switch that changes nothing. Both
        modes are stated."""
        root = self._corpus(("BG0001", "Open", "Medium", "m"))
        with self.assertRaises(SystemExit) as caught:
            ki.main(["--root", str(root)])
        self.assertEqual(2, caught.exception.code)

    def test_write_then_check_agrees(self):
        """The positive control. Without it, a `--check` that always refused would pass the test
        above for entirely the wrong reason."""
        root = self._corpus(("BG0001", "Open", "Medium", "m"))
        self.assertEqual(0, ki.main(["--write", "--root", str(root)]))
        self.assertEqual(0, ki.main(["--check", "--root", str(root)]))


class ReleaseBarTests(unittest.TestCase):
    """The bar itself: `--bar` is what makes "zero open High" a check rather than a sentence.

    Deliberately NOT asserted against the live corpus here. An open High finding is ordinary
    mid-sprint and is a defect only at the tag, so a per-commit test that demanded zero would
    be red for most of a release cycle and would be switched off. The behaviour is pinned on
    fixtures; the live reading belongs on the release path.
    """

    def _corpus(self, *bugs):
        root = Path(tempfile.mkdtemp(prefix="release_bar_"))
        (root / ki.BUGS_REL).mkdir(parents=True)
        (root / "docs").mkdir(parents=True)
        for bug_id, status, severity in bugs:
            (root / ki.BUGS_REL / f"{bug_id}-x.md").write_text(
                f"# {bug_id}: t\n\n> **Status:** {status}\n> **Severity:** {severity}\n",
                encoding="utf-8")
        return root

    def test_an_open_high_finding_fails_the_bar(self):
        root = self._corpus(("BG0001", "Open", "High"), ("BG0002", "Open", "Medium"))
        self.assertEqual(1, ki.main(["--bar", "--root", str(root)]))

    def test_an_open_critical_finding_fails_the_bar(self):
        """Critical is barred too. A bar that only reads High would let the worse case through."""
        root = self._corpus(("BG0001", "Open", "Critical"))
        self.assertEqual(1, ki.main(["--bar", "--root", str(root)]))

    def test_a_disclosed_residue_alone_meets_the_bar(self):
        """The positive control, and the whole point of D0136: Medium and Low ship OPEN."""
        root = self._corpus(("BG0001", "Open", "Medium"), ("BG0002", "Open", "Low"))
        self.assertEqual(0, ki.main(["--bar", "--root", str(root)]))

    def test_a_fixed_high_finding_does_not_hold_the_bar(self):
        root = self._corpus(("BG0001", "Fixed", "High"), ("BG0002", "Won't Fix", "High"))
        self.assertEqual(0, ki.main(["--bar", "--root", str(root)]))

    def test_the_bar_and_the_residue_are_separate_reads(self):
        """Folding the bar into a filter over the disclosed set is how a residue check ends up
        standing in for a bar check. A High finding must appear in NEITHER list."""
        root = self._corpus(("BG0001", "Open", "High"))
        self.assertEqual({}, ki.corpus(root))
        self.assertEqual({"BG0001": "High"}, ki.barred_open(root))


class BarPopulationTests(unittest.TestCase):
    """BG0621 - WHICH findings the bar and the page can see at all.

    ReleaseBarTests above pins what the bar DECIDES for a finding it reads. This class pins the
    prior question: whether it reads the finding. Three guards each skipped one, and a finding
    skipped is indistinguishable from a clean bill of health - which is what makes a bar that
    can answer MET while a High is open worse than no bar.
    """

    def _corpus(self, *bugs, heading="# {id}: t"):
        root = Path(tempfile.mkdtemp(prefix="bar_population_"))
        (root / ki.BUGS_REL).mkdir(parents=True)
        (root / "docs").mkdir(parents=True)
        for bug_id, status, severity in bugs:
            (root / ki.BUGS_REL / f"{bug_id}-x.md").write_text(
                f"{heading.format(id=bug_id)}\n\n> **Status:** {status}\n"
                f"> **Severity:** {severity}\n", encoding="utf-8")
        return root

    def test_severity_is_matched_regardless_of_casing(self):
        """MUTANT: in `known_issues.py`, compare the severity against `BARRED` without
        normalising case, as the shipped guard does.

        `BARRED` is a tuple of capitalised strings and `file_finding.py` does not normalise the
        field, so the corpus holds seven bugs written `high`. A bar whose answer depends on how
        somebody typed is not a bar."""
        root = self._corpus(("BG0001", "Open", "high"), ("BG0002", "Open", "CRITICAL"))
        self.assertEqual({"BG0001": "high", "BG0002": "CRITICAL"}, ki.barred_open(root))
        self.assertEqual(1, ki.main(["--bar", "--root", str(root)]))

    def test_every_non_terminal_status_counts_as_open(self):
        """MUTANT: in `known_issues.py`, restore the `!= "Open"` literal-status test in place of
        the not-terminal test.

        `In Progress` is a legitimate bug status and the resting state of a bug somebody is
        halfway through fixing. Reading only the literal `Open` made the bar answer MET for
        exactly the finding most likely to be in flight when somebody asks. `Blocked` is NOT in
        the bug vocabulary at all, and is here on purpose: an out-of-vocabulary status must fall
        OPEN, so a typo or a project-declared status over-refuses rather than hides."""
        root = self._corpus(("BG0001", "In Progress", "High"), ("BG0002", "Blocked", "High"))
        self.assertEqual({"BG0001": "High", "BG0002": "High"}, ki.barred_open(root))
        self.assertEqual(1, ki.main(["--bar", "--root", str(root)]))

    def test_a_hyphenated_heading_is_still_read(self):
        """MUTANT: in `known_issues.py`, narrow `_HEADING` back to `^# (BG\\d+): (.+)$`, so a
        hyphenated id no longer matches.

        21 files in this corpus write their H1 as `# BG-0123:`. A heading that does not match
        skips the WHOLE file, taking its status and severity with it - the finding does not
        merely lose its title, it leaves the population."""
        root = self._corpus(("BG0001", "Open", "High"), heading="# BG-0001: t")
        self.assertEqual({"BG-0001": "High"}, ki.barred_open(root))
        self.assertEqual(1, ki.main(["--bar", "--root", str(root)]))

    def test_an_unparseable_finding_is_reported_not_dropped(self):
        """MUTANT: in `known_issues.py`, drop the unparseable-finding report and `continue`
        silently, as the shipped guard does.

        This is what the three hatches have in common, and the only guard that covers the fourth
        shape nobody has thought of yet. A file the readers cannot parse must never be silently
        absent from a release bar."""
        root = self._corpus(("BG0001", "Fixed", "High"))     # nothing else can refuse the bar
        self.assertEqual(0, ki.main(["--bar", "--root", str(root)]),
                         "the control must pass BEFORE the unreadable file is added, or this "
                         "test cannot tell which finding refused")
        (root / ki.BUGS_REL / "BG0002-x.md").write_text("nothing parseable here\n",
                                                        encoding="utf-8")
        self.assertEqual(["sdlc-studio/bugs/BG0002-x.md"], ki.unparseable(root))
        self.assertEqual(1, ki.main(["--bar", "--root", str(root)]),
                         "an unreadable finding is the ONLY thing wrong with this corpus, so "
                         "the bar refusing proves it was the unreadable file that did it")

    def test_a_clean_corpus_still_reports_the_bar_met(self):
        """The paired control. Widening the population must not turn the bar into a check that
        can never pass - a gate that always refuses is switched off within the week."""
        root = self._corpus(("BG0001", "Open", "Medium"), ("BG0002", "Fixed", "High"),
                            ("BG0003", "Won't Fix", "Critical"), ("BG0004", "Closed", "high"),
                            # a lowercase TERMINAL status, which pins `_is_open`'s casefold the
                            # way BG0004 pins `_matches`'. Without it, dropping that casefold
                            # left every test in this file green.
                            ("BG0005", "fixed", "High"))
        self.assertEqual({}, ki.barred_open(root))
        self.assertEqual([], ki.unparseable(root))
        self.assertEqual(0, ki.main(["--bar", "--root", str(root)]))

    def test_the_live_corpus_has_no_unparseable_finding(self):
        """MUTANT: in `known_issues.py`, narrow `_HEADING` back so a hyphenated id no longer
        matches - 21 live files then become unreadable.

        The mutant is a HEADING change rather than a `--bar` change because this test reads the
        corpus in-process and never calls `main`: deleting the report from the CLI path leaves it
        green, which was the declaration it carried until a review executed it.

        Deliberately against the LIVE corpus, not a fixture. The fixture test above proves the
        guard CAN see an unreadable finding; this one proves it was pointed at the real thing.
        Its first run found BG0131, invisible to both readers since 2026-07-14 because its H1
        carried a parenthetical between the id and the colon - a guard whose first execution over
        real data finds nothing has not been shown to look."""
        self.assertEqual([], ki.unparseable(),
                         "a finding neither the bar nor the disclosure page can parse is "
                         "invisible to both, and invisible reads exactly like clean")

    def test_check_and_write_also_report_an_unreadable_finding(self):
        """MUTANT: in `known_issues.py`, drop the `_warn_unparseable` call from the check/write
        path, leaving the report on `--bar` alone.

        The bar runs at a release boundary; `--check` runs every commit. Warning only at the
        boundary is how BG0131 sat unread from 2026-07-14 - LL0027, a gate belongs in the command
        people actually run."""
        root = self._corpus(("BG0001", "Open", "Medium"))
        (root / ki.BUGS_REL / "BG0002-x.md").write_text("nothing parseable\n", encoding="utf-8")
        (root / "docs" / "known-issues.md").write_text(ki.render(root), encoding="utf-8")
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            rc = ki.main(["--check", "--root", str(root)])
        self.assertEqual(0, rc, "the page agrees with the corpus, so --check must still pass")
        self.assertIn("BG0002-x.md", err.getvalue(),
                      "an unreadable finding must be named on the per-commit path, not only at "
                      "the release boundary")

    def test_the_terminal_set_matches_the_shipped_bug_vocabulary(self):
        """`TERMINAL` is a hand-copy of what `sdlc_md` already owns, so it can only drift. A
        terminal status added to the vocabulary later would read as OPEN here and the bar would
        over-refuse - safe, but silent, and nobody would connect the two."""
        sys.path.insert(0, str(Path(__file__).resolve().parents[2]
                               / ".claude/skills/sdlc-studio/scripts/lib"))
        import sdlc_md  # noqa: PLC0415 - deferred; tools/ does not import skill internals at load
        self.assertEqual(set(sdlc_md.TERMINAL_STATUS["bug"]), set(ki.TERMINAL),
                         "known_issues.TERMINAL has drifted from the shipped bug vocabulary")

    def test_the_disclosure_page_reads_the_same_population_as_the_bar(self):
        """MUTANT: in `known_issues.py`, leave the page's population reader on the old three
        guards while the bar uses the new ones.

        `corpus` renders the disclosure page and repeats all three guards verbatim. A release is
        judged on the page as well as on the bar, so repairing one and not the other leaves the
        defect standing in the file it was found in."""
        root = self._corpus(("BG0001", "In Progress", "medium"), heading="# BG-0001: t")
        self.assertEqual({"BG-0001": ("medium", "t")}, ki.corpus(root))



class ReleaseNotesClaimTests(unittest.TestCase):
    """The hand-authored notes state a count in prose. Prose drifts; this is what stops it."""

    def test_the_notes_state_the_number_of_findings_the_corpus_holds(self):
        notes = (ki.REPO / ki.NOTES_REL).read_text(encoding="utf-8")
        found = ki.corpus()
        mediums = sum(1 for s, _t in found.values() if s == "Medium")
        lows = sum(1 for s, _t in found.values() if s == "Low")
        # Version read from the file the guard points at, not hardcoded - the assertion must
        # follow NOTES_REL when it moves to the next release rather than pinning a dead one.
        version = ki.NOTES_REL.rsplit("release-notes-", 1)[1].removesuffix(".md")
        expected = (f"**{version} discloses {len(found)} open defects: {mediums} Medium, "
                    f"{lows} Low.**")
        self.assertIn(
            expected, notes,
            "the release notes state a finding count the bug corpus contradicts. It should "
            f"read:\n  {expected}")

    def test_the_notes_do_not_claim_zero_high_while_the_corpus_holds_one(self):
        """The half of the claim that was NOT derived, and therefore drifted.

        This guard's docstring says "prose drifts; this is what stops it", and it then pinned
        the Medium and Low counts against the corpus while hardcoding `Zero Critical, zero High`
        as a literal - so the one clause nothing measured was the one that went false. Four High
        findings were raised against v5.0.1 after its tag and the assertion stayed green,
        because the string it demanded was the string it supplied.

        A barred finding must be NAMED in the notes, not merely counted: `--bar` prints ids, and
        an operator reconciling the two reads ids.
        """
        notes = (ki.REPO / ki.NOTES_REL).read_text(encoding="utf-8")
        barred = ki.barred_open()
        if not barred:
            self.assertIn("Zero Critical, zero High.", notes,
                          "the corpus holds no barred finding, so the notes should say so")
            return
        self.assertNotIn(
            "Zero Critical, zero High.**", notes,
            f"the notes claim zero barred findings while the corpus holds {len(barred)}: "
            f"{', '.join(sorted(barred))}")
        for uid in sorted(barred):
            self.assertIn(uid, notes,
                          f"{uid} is open at a barred severity and the release notes do not "
                          f"name it - `--bar` names ids, so the prose must too")


class DepthFieldCountsTests(unittest.TestCase):
    """A `Verification depth` field states counts the artefact can contradict.

    That field has been wrong on this repository's units in every review round of
    RUN-01M0CT8P - criterion counts, mutant counts, and claims about what was executed. The
    counts are derivable, so a disagreement is mechanically checkable and does not need a
    reviewer to notice it. CR0548 proposes deriving the field outright; until then this refuses
    the one part of it that can be checked.
    """

    WORDS = {"one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6, "seven": 7,
             "eight": 8, "nine": 9, "ten": 10, "eleven": 11, "twelve": 12}

    def test_no_depth_field_states_a_criterion_count_the_artefact_contradicts(self) -> None:
        repo = Path(__file__).resolve().parents[2]
        units = sorted((repo / "sdlc-studio" / "bugs").glob("*.md"))
        self.assertGreater(len(units), 50,
                           f"only {len(units)} bug artefacts found - the census resolved the "
                           f"wrong root and measures nothing")
        wrong = []
        for f in units:
            text = f.read_text(encoding="utf-8")
            m = re.search(r"^> \*\*Verification depth:\*\* (.*)$", text, re.M)
            if not m:
                continue
            stated = re.search(r"\b(\w+) criteri(?:on|a)\b", m.group(1))
            if not stated:
                continue
            word = stated.group(1).lower()
            n = self.WORDS.get(word) or (int(word) if word.isdigit() else None)
            if n is None:
                continue
            actual = len(re.findall(r"^- \[[x ]\] \*\*AC\d+\*\*", text, re.M))
            if actual and n != actual:
                wrong.append(f"{f.name.split('-')[0]}: depth says {n}, artefact has {actual}")
        self.assertEqual([], wrong,
                         "these `Verification depth` fields state a criterion count the artefact "
                         "contradicts - the field a reviewer reads first, disagreeing with the "
                         "unit it describes:\n" + "\n".join(wrong))


if __name__ == "__main__":
    unittest.main()
